library(checkmate)
library(dplyr)
library(prettycheck)
library(scaler)
library(testthat)

test_check("scaler")

# # For development use only (comment the code after use (Ctrl + Shift + C)).
#
# .rs.restartR()
# cffr::cff_write()
# codemetar::write_codemeta()
# covr::package_coverage()
# devtools::check()
# devtools::document()
# devtools::install()
# devtools::release()
# devtools:test()
# goodpractice::gp()
# lintr::use_lintr(type = "tidyverse")
# lintr::lint_package()
# normalizePath(readClipboard(), "/", mustWork = FALSE)
# pkgdown::build_article()
# pkgdown::build_favicons()
# pkgdown::build_reference()
# pkgdown::build_site()
# roxygen2::update_collate(".")
# spelling::spell_check_package()
# spelling::update_wordlist()
# stringi::stri_escape_unicode("└─")
# urlchecker::url_check()
# usethis::use_coverage()
# usethis::use_github_action("check-release")
# usethis::use_logo(file.choose())
# usethis::use_tidy_description()
